language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm

before_script:
  - mkdir -p cache
  - composer install

script:
  - vendor/bin/phpunit
